import { Link } from 'react-router-dom';
import { Zap, Clock, Shield, ArrowRight } from 'lucide-react';

export function Landing() {
  return (
    <div className="min-h-screen bg-zinc-950 text-white">
      {/* Nav */}
      <nav className="px-6 py-5">
        <div className="mx-auto flex max-w-5xl items-center justify-between">
          <div className="text-xl font-bold tracking-tight">
            <span className="text-emerald-400">FORGE</span>3D
          </div>
          <div className="flex gap-4">
            <Link to="/login" className="text-sm text-zinc-400 hover:text-white transition">Log in</Link>
            <Link to="/orders/new" className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium hover:bg-emerald-500 transition">
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="mx-auto max-w-3xl px-6 py-24 text-center">
        <div className="mb-4 inline-block rounded-full border border-emerald-500/30 bg-emerald-500/10 px-4 py-1.5 text-xs font-medium text-emerald-400">
          AI-Powered 3D Production
        </div>
        <h1 className="text-5xl font-bold leading-tight tracking-tight">
          Professional 3D assets,
          <br />
          <span className="text-emerald-400">delivered in hours.</span>
        </h1>
        <p className="mx-auto mt-6 max-w-xl text-lg text-zinc-400">
          Product renders, 3D print files, and rapid prototypes — generated by AI, reviewed by humans.
          Skip the 5-day wait. Get production-ready assets today.
        </p>
        <div className="mt-10 flex items-center justify-center gap-4">
          <Link
            to="/orders/new"
            className="flex items-center gap-2 rounded-xl bg-emerald-600 px-8 py-3.5 font-medium hover:bg-emerald-500 transition"
          >
            Start an Order <ArrowRight size={18} />
          </Link>
          <a href="#pricing" className="rounded-xl border border-zinc-800 px-8 py-3.5 font-medium text-zinc-300 hover:border-zinc-600 transition">
            See Pricing
          </a>
        </div>
      </section>

      {/* Features */}
      <section className="mx-auto max-w-4xl px-6 py-16">
        <div className="grid gap-6 md:grid-cols-3">
          {[
            { icon: <Zap size={24} />, title: 'AI-Generated', desc: 'Blender + Claude Code produce your assets autonomously. Same quality, fraction of the time.' },
            { icon: <Clock size={24} />, title: 'Hours, Not Days', desc: 'Product renders in under 2 hours. Custom STL files in minutes. Rush delivery available.' },
            { icon: <Shield size={24} />, title: 'Production Ready', desc: 'Cycles-rendered at 2048px. Print files validated for manifold geometry. Ready to ship.' },
          ].map((f, i) => (
            <div key={i} className="rounded-xl border border-zinc-800 bg-zinc-900/30 p-6">
              <div className="mb-3 text-emerald-400">{f.icon}</div>
              <h3 className="mb-2 font-semibold">{f.title}</h3>
              <p className="text-sm text-zinc-500">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="mx-auto max-w-4xl px-6 py-16">
        <h2 className="mb-8 text-center text-3xl font-bold">Simple Pricing</h2>
        <div className="grid gap-4 md:grid-cols-3">
          {[
            { name: 'Product Render', price: '$100', desc: 'Photorealistic mockup, 2048px PNG, styled lighting' },
            { name: '3D Print File', price: '$50', desc: 'Custom STL/3MF, validated geometry, print-ready' },
            { name: 'Rapid Prototype', price: '$150', desc: 'STEP file for manufacturing, iterative revisions' },
          ].map((tier, i) => (
            <div key={i} className="rounded-xl border border-zinc-800 p-6 text-center">
              <h3 className="font-semibold">{tier.name}</h3>
              <div className="my-3 text-3xl font-bold text-emerald-400">{tier.price}</div>
              <p className="text-sm text-zinc-500">{tier.desc}</p>
              <Link to="/orders/new" className="mt-4 block rounded-lg bg-zinc-800 py-2 text-sm font-medium hover:bg-zinc-700 transition">
                Order Now
              </Link>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-zinc-900 px-6 py-8 text-center text-sm text-zinc-600">
        © {new Date().getFullYear()} FORGE3D — A PNW Solutions Product · 1Commerce Ecosystem
      </footer>
    </div>
  );
}
